import { ClientLocation } from "@/types";

export const clientLocations: ClientLocation[] = [
  {
    id: "c1",
    name: "Tech Startup",
    role: "SaaS Product Team",
    country: "Vietnam",
    quote: {
      en: "KhaiFrost helped us reduce 60% of our development time. Their team understood our roadmap quickly and shipped features we thought would take months in just weeks.",
      vi: "KhaiFrost đã giúp chúng tôi giảm 60% thời gian phát triển. Đội ngũ của họ nắm bắt lộ trình rất nhanh và triển khai những tính năng mà chúng tôi nghĩ phải mất hàng tháng chỉ trong vài tuần.",
    },
    avatar: "/images/placeholders/testimonial-1.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 78,
    y: 52,
  },
  {
    id: "c2",
    name: "Product Team",
    role: "E-commerce Platform",
    country: "United States",
    quote: {
      en: "The AI assistant is a game changer for our team. Support tickets dropped by half and our customers get answers instantly, even outside business hours.",
      vi: "Trợ lý AI đã thay đổi hoàn toàn cách đội ngũ chúng tôi làm việc. Số lượng yêu cầu hỗ trợ giảm một nửa và khách hàng nhận được câu trả lời ngay lập tức, kể cả ngoài giờ làm việc.",
    },
    avatar: "/images/placeholders/testimonial-2.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 20,
    y: 45,
  },
  {
    id: "c3",
    name: "Business Owner",
    role: "Logistics & Supply Chain",
    country: "Singapore",
    quote: {
      en: "Very professional and high quality product. From onboarding to deployment, KhaiFrost's engineers were responsive and clearly explained every step of the process.",
      vi: "Sản phẩm rất chuyên nghiệp và chất lượng cao. Từ giai đoạn onboarding đến triển khai, đội ngũ kỹ sư của KhaiFrost luôn phản hồi nhanh và giải thích rõ ràng từng bước trong quy trình.",
    },
    avatar: "/images/placeholders/testimonial-4.jpg",
    coverImage: "/images/map/covers/warehouse.jpg",
    x: 75.2,
    y: 53.5,
  },
  {
    id: "c4",
    name: "CEO",
    role: "Fintech Startup",
    country: "Japan",
    quote: {
      en: "We've seen real growth since using KhaiFrost. Their cloud infrastructure work gave us the stability to scale to thousands of daily active users without downtime.",
      vi: "Chúng tôi đã tăng trưởng rõ rệt kể từ khi sử dụng KhaiFrost. Hạ tầng cloud mà họ xây dựng giúp chúng tôi mở rộng ổn định đến hàng nghìn người dùng hoạt động mỗi ngày mà không gặp gián đoạn.",
    },
    avatar: "/images/placeholders/testimonial-5.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 85.8,
    y: 37.2,
  },
  {
    id: "c5",
    name: "Engineer",
    role: "IoT Manufacturing",
    country: "Australia",
    quote: {
      en: "The best dev tool we've ever used. Clean code, solid documentation, and a team that actually cares about long-term maintainability, not just quick fixes.",
      vi: "Đây là công cụ phát triển tốt nhất chúng tôi từng sử dụng. Code sạch, tài liệu đầy đủ, và đội ngũ thực sự quan tâm đến khả năng bảo trì lâu dài chứ không chỉ những bản sửa nhanh.",
    },
    avatar: "/images/placeholders/testimonial-6.jpg",
    coverImage: "/images/map/covers/factory.jpg",
    x: 89.1,
    y: 70.3,
  },
  {
    id: "c6",
    name: "Developer",
    role: "Healthcare Software",
    country: "United Kingdom",
    quote: {
      en: "Great support and super clean code. Security and compliance were handled with real care, which mattered a lot for a healthcare product like ours.",
      vi: "Hỗ trợ tuyệt vời và code cực kỳ sạch sẽ. Vấn đề bảo mật và tuân thủ quy định được xử lý rất cẩn thận, điều rất quan trọng đối với một sản phẩm y tế như của chúng tôi.",
    },
    avatar: "/images/placeholders/testimonial-3.jpg",
    coverImage: "/images/map/covers/healthcare.jpg",
    x: 44.6,
    y: 29.6,
  },
  {
    id: "c7",
    name: "CTO",
    role: "Automotive Software",
    country: "Germany",
    quote: {
      en: "KhaiFrost's DevOps pipeline cut our release cycle from two weeks to two days. The precision and reliability match what we expect from German engineering standards.",
      vi: "Pipeline DevOps của KhaiFrost đã rút ngắn chu kỳ phát hành của chúng tôi từ hai tuần xuống còn hai ngày. Độ chính xác và tin cậy đáp ứng đúng tiêu chuẩn kỹ thuật khắt khe mà chúng tôi kỳ vọng.",
    },
    avatar: "/images/placeholders/testimonial-1.jpg",
    coverImage: "/images/map/covers/factory.jpg",
    x: 48.6,
    y: 29.1,
  },
  {
    id: "c8",
    name: "Head of Retail Tech",
    role: "Retail Technology",
    country: "France",
    quote: {
      en: "Our in-store and online systems finally talk to each other. KhaiFrost built the integration layer that made omnichannel retail actually work for us.",
      vi: "Hệ thống tại cửa hàng và trực tuyến của chúng tôi cuối cùng đã đồng bộ với nhau. KhaiFrost đã xây dựng lớp tích hợp giúp mô hình bán lẻ đa kênh thực sự vận hành hiệu quả.",
    },
    avatar: "/images/placeholders/testimonial-2.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 45.3,
    y: 30.9,
  },
  {
    id: "c9",
    name: "Founder",
    role: "Edtech Platform",
    country: "Canada",
    quote: {
      en: "We scaled from 5,000 to 200,000 students on the same architecture KhaiFrost designed. No rewrites, no downtime during exam season, just steady growth.",
      vi: "Chúng tôi đã mở rộng từ 5.000 lên 200.000 học sinh trên cùng một kiến trúc do KhaiFrost thiết kế. Không cần viết lại hệ thống, không gián đoạn trong mùa thi, chỉ có tăng trưởng ổn định.",
    },
    avatar: "/images/placeholders/testimonial-3.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 21.2,
    y: 33.4,
  },
  {
    id: "c10",
    name: "Head of Payments",
    role: "Payments & Fintech",
    country: "Brazil",
    quote: {
      en: "Handling millions of transactions a day requires zero tolerance for downtime. KhaiFrost's infrastructure has kept us running at 99.99% uptime for over a year.",
      vi: "Xử lý hàng triệu giao dịch mỗi ngày đòi hỏi không được phép gián đoạn. Hạ tầng do KhaiFrost xây dựng đã giúp chúng tôi duy trì uptime 99.99% trong hơn một năm qua.",
    },
    avatar: "/images/placeholders/testimonial-4.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 30.9,
    y: 65.4,
  },
  {
    id: "c11",
    name: "VP of Engineering",
    role: "Real Estate Tech",
    country: "United Arab Emirates",
    quote: {
      en: "From property listings to smart contracts, KhaiFrost helped us launch three major features in one quarter without adding a single engineer to our team.",
      vi: "Từ danh sách bất động sản đến hợp đồng thông minh, KhaiFrost đã giúp chúng tôi ra mắt ba tính năng lớn chỉ trong một quý mà không cần tuyển thêm kỹ sư nào.",
    },
    avatar: "/images/placeholders/testimonial-5.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 60.9,
    y: 42.1,
  },
  {
    id: "c12",
    name: "Engineering Manager",
    role: "Cloud Infrastructure",
    country: "India",
    quote: {
      en: "KhaiFrost's AWS architecture review saved us nearly 40% on our monthly cloud bill while actually improving response times across every region we serve.",
      vi: "Buổi review kiến trúc AWS của KhaiFrost đã giúp chúng tôi tiết kiệm gần 40% chi phí cloud hàng tháng, đồng thời cải thiện tốc độ phản hồi ở mọi khu vực chúng tôi phục vụ.",
    },
    avatar: "/images/placeholders/testimonial-6.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 67.4,
    y: 40.5,
  },
  {
    id: "c13",
    name: "Product Lead",
    role: "Consumer Electronics",
    country: "South Korea",
    quote: {
      en: "Firmware updates used to be our biggest headache. KhaiFrost built an OTA pipeline that now pushes updates to over a million devices with zero failed rollouts.",
      vi: "Cập nhật firmware từng là vấn đề đau đầu nhất của chúng tôi. KhaiFrost đã xây dựng pipeline OTA giúp đẩy bản cập nhật đến hơn một triệu thiết bị mà không gặp lỗi triển khai nào.",
    },
    avatar: "/images/placeholders/testimonial-1.jpg",
    coverImage: "/images/map/covers/factory.jpg",
    x: 82,
    y: 36.3,
  },
  {
    id: "c14",
    name: "Plant Director",
    role: "Manufacturing ERP",
    country: "China",
    quote: {
      en: "Connecting three factory floors into one ERP system sounded impossible until KhaiFrost mapped it out. Production reporting that took days now happens in real time.",
      vi: "Việc kết nối ba nhà máy vào chung một hệ thống ERP từng tưởng như bất khả thi cho đến khi KhaiFrost lên phương án. Báo cáo sản xuất từng mất nhiều ngày giờ đây cập nhật theo thời gian thực.",
    },
    avatar: "/images/placeholders/testimonial-2.jpg",
    coverImage: "/images/map/covers/factory.jpg",
    x: 80.4,
    y: 39.3,
  },
  {
    id: "c15",
    name: "Operations Director",
    role: "Mining & Logistics",
    country: "South Africa",
    quote: {
      en: "Tracking equipment and shipments across remote sites was a nightmare on spreadsheets. KhaiFrost's dashboard gives us live visibility across our entire supply chain.",
      vi: "Việc theo dõi thiết bị và lô hàng qua các công trường xa xôi từng là ác mộng khi dùng spreadsheet. Dashboard của KhaiFrost giúp chúng tôi giám sát trực tiếp toàn bộ chuỗi cung ứng.",
    },
    avatar: "/images/placeholders/testimonial-3.jpg",
    coverImage: "/images/map/covers/warehouse.jpg",
    x: 52.9,
    y: 66.6,
  },
  {
    id: "c16",
    name: "Co-founder",
    role: "Agri-Tech",
    country: "Netherlands",
    quote: {
      en: "Our sensor data from greenhouses across Europe now flows into one platform KhaiFrost built for us, helping farmers cut water usage by nearly a third.",
      vi: "Dữ liệu cảm biến từ các nhà kính khắp châu Âu giờ đây đổ về một nền tảng duy nhất do KhaiFrost xây dựng, giúp nông dân giảm gần một phần ba lượng nước sử dụng.",
    },
    avatar: "/images/placeholders/testimonial-4.jpg",
    coverImage: "/images/map/covers/warehouse.jpg",
    x: 46.1,
    y: 29.2,
  },
  {
    id: "c17",
    name: "Regional Manager",
    role: "Hospitality Tech",
    country: "Thailand",
    quote: {
      en: "Booking, check-in and housekeeping used to run on three separate systems. KhaiFrost unified them into one app our staff actually enjoys using every day.",
      vi: "Đặt phòng, check-in và dọn phòng từng chạy trên ba hệ thống riêng biệt. KhaiFrost đã hợp nhất chúng thành một ứng dụng mà nhân viên chúng tôi thực sự thích sử dụng mỗi ngày.",
    },
    avatar: "/images/placeholders/testimonial-5.jpg",
    coverImage: "/images/map/covers/office.jpg",
    x: 74.2,
    y: 47.6,
  },
  {
    id: "c18",
    name: "Medical Director",
    role: "Telehealth",
    country: "Indonesia",
    quote: {
      en: "Reaching patients across thousands of islands is only possible with reliable infrastructure. KhaiFrost's platform now connects doctors and patients across the whole archipelago.",
      vi: "Việc tiếp cận bệnh nhân trên hàng nghìn hòn đảo chỉ khả thi khi có hạ tầng đáng tin cậy. Nền tảng của KhaiFrost hiện kết nối bác sĩ và bệnh nhân trên khắp quần đảo.",
    },
    avatar: "/images/placeholders/testimonial-6.jpg",
    coverImage: "/images/map/covers/healthcare.jpg",
    x: 76.1,
    y: 57.1,
  },
];
